### ISSUE TITLE
MFP not defined angular 6 mfp web sdk

### ISSUE THREAD

**Issue by srikanthmk** [vittalpai/mfp-userlogin-angular#1]
Hi vittalpai,
I am getting the below error while building the application (ng serve) on terminal ,

ERROR in src/app/app.component.ts(12,33): error TS2694: Namespace 'WL' has no exported member 'Client'.
src/app/app.component.ts(15,8): error TS2339: Property 'Client' does not exist on type 'typeof WL'.
src/app/app.component.ts(40,41): error TS2339: Property 'Client' does not exist on type 'typeof WL'.

On browser console below errors are thrown:

MFP is not defined,  WL is not defined at new AppComponent (app.component.ts:15)

Thanks in advance.

**Comment by vittalpai** [comment]
@srikanthmk Did you run `npm install` before running the application ?

**Comment by srikanthmk** [comment]
hi vittalpai,
i run the npm install command and after run the application(ng serve)


still facing the same issue,


on terminal-
ERROR in src/app/app.component.ts(12,33): error TS2694: Namespace 'WL' has no exported member 'Client'.
src/app/app.component.ts(15,8): error TS2339: Property 'Client' does not exist on type 'typeof WL'.
src/app/app.component.ts(40,41): error TS2339: Property 'Client' does not exist on type 'typeof WL'.

**Comment by vittalpai** [comment]
@srikanthmk Can you forward me the commands which you ran to run this app ?

**Comment by srikanthmk** [comment]
on project folder
mfp-userlogin-angular$: sudo npm install --allow-root

Here i am getting the below 2 build errors ,
stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js 
stack Error: EACCES: permission denied, mkdir '/Users/myuser/Desktop/mymobileUKOB/mfp-userlogin-angular/node_modules/node-sass/build'

2nd command
mfp-userlogin-angular$: sudo ng serve
here my default server is localhost:4200 ,
error,

ERROR in src/app/app.component.ts(12,33): error TS2694: Namespace 'WL' has no exported member 'Client'.
src/app/app.component.ts(15,8): error TS2339: Property 'Client' does not exist on type 'typeof WL'.
src/app/app.component.ts(40,41): error TS2339: Property 'Client' does not exist on type 'typeof WL'.

**Comment by vittalpai** [comment]
@srikanthmk Try with following command.
`npm install --unsafe-perm --force`

https://github.com/angular/angular-cli/issues/6848

**Comment by srikanthmk** [comment]
@vittalpai , Now its compiling successfully, but we are getting  errors in browser console,
before its compiling, we did some changes

var resourceRequest = new WL.ResourceRequest("/adapters/ResourceAdapter/balance",WL.ResourceRequest.GET);

To

var resourceRequest = new resourceRequest("/adapters/ResourceAdapter/balance",resourceRequest.GET);
and replaced al WL to MFP.

Browser console errors,
ibmmfpf.js:1423 Uncaught ReferenceError: MFP is not defined
    at ibmmfpf.js:1423
    at ibmmfpf.js:44
    at ibmmfpf.js:85
(anonymous) @ ibmmfpf.js:1423
(anonymous) @ ibmmfpf.js:44
(anonymous) @ ibmmfpf.js:85
ibmmfpf.js:1335 ERROR ReferenceError: MFP is not defined
    at new AppComponent (app.component.ts:16)
    at createClass (core.js:22050)
    at createDirectiveInstance (core.js:21931)
    at createViewNodes (core.js:23157)
    at createRootView (core.js:23071)
    at callWithDebugContext (core.js:24079)
    at Object.debugCreateRootView [as createRootView] (core.js:23589)
    at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (core.js:21410)
    at ComponentFactoryBoundToModule.push../node_modules/@angular/core/fesm5/core.js.ComponentFactoryBoundToModule.create (core.js:9933)
    at bound.push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.bootstrap (core.js:17990)
bound @ ibmmfpf.js:1335
View_AppComponent_Host_0 @ AppComponent_Host.ngfactory.js? [sm]:1
proxyClass @ compiler.js:18234
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:24041
bound @ ibmmfpf.js:1335
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15762
(anonymous) @ core.js:17860
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17248
(anonymous) @ core.js:17860
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.js:17289
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
(anonymous) @ zone.js:889
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:17280
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
Promise.then (async)
scheduleMicroTask @ zone.js:584
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:258
scheduleResolveOrReject @ zone.js:879
ZoneAwarePromise.then @ zone.js:1012
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:17793
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:78
0 @ main.ts:12
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
ibmmfpf.js:1335 ERROR CONTEXT DebugContext_ {view: {…}, nodeIndex: 1, nodeDef: {…}, elDef: {…}, elView: {…}}
bound @ ibmmfpf.js:1335
View_AppComponent_Host_0 @ AppComponent_Host.ngfactory.js? [sm]:1
proxyClass @ compiler.js:18234
push../node_modules/@angular/core/fesm5/core.js.DebugContext_.logError @ core.js:24041
bound @ ibmmfpf.js:1335
push../node_modules/@angular/core/fesm5/core.js.ErrorHandler.handleError @ core.js:15767
(anonymous) @ core.js:17860
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular @ core.js:17248
(anonymous) @ core.js:17860
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:391
onInvoke @ core.js:17289
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:390
push../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:150
(anonymous) @ zone.js:889
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
onInvokeTask @ core.js:17280
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
drainMicroTaskQueue @ zone.js:601
Promise.then (async)
scheduleMicroTask @ zone.js:584
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:413
push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
push../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:258
scheduleResolveOrReject @ zone.js:879
ZoneAwarePromise.then @ zone.js:1012
push../node_modules/@angular/core/fesm5/core.js.PlatformRef.bootstrapModule @ core.js:17793
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap:78
0 @ main.ts:12
__webpack_require__ @ bootstrap:78
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
main.ts:12 ReferenceError: MFP is not defined
    at new AppComponent (app.component.ts:16)
    at createClass (core.js:22050)
    at createDirectiveInstance (core.js:21931)
    at createViewNodes (core.js:23157)
    at createRootView (core.js:23071)
    at callWithDebugContext (core.js:24079)
    at Object.debugCreateRootView [as createRootView] (core.js:23589)
    at ComponentFactory_.push../node_modules/@angular/core/fesm5/core.js.ComponentFactory_.create (core.js:21410)
    at ComponentFactoryBoundToModule.push../node_modules/@angular/core/fesm5/core.js.ComponentFactoryBoundToModule.create (core.js:9933)
    at bound.push../node_modules/@angular/core/fesm5/core.js.ApplicationRef.bootstrap (core.js:17990)

**Comment by vittalpai** [comment]
@srikanthmk WRONG. You are not supposed to replace WL with MFP.

**Comment by srikanthmk** [comment]
ok reverted the code, now  below error thrown in terminal.

ERROR in src/app/app.component.ts(13,33): error TS2694: Namespace 'WL' has no exported member 'Client'.
src/app/app.component.ts(16,8): error TS2339: Property 'Client' does not exist on type 'typeof WL'.
src/app/app.component.ts(41,41): error TS2339: Property 'Client' does not exist on type 'typeof WL'.

**Comment by vittalpai** [comment]
Seems to be you haven't installed MFP SDK properly.

Catch me on MobileFirst Slack Channel : https://mobilefirstplatform.ibmcloud.com/blog/2017/05/26/come-chat-with-us/
